apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    app: nginx
spec:
  containers:
  - name: readiness
    image: registry.k8s.io/busybox
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - ls
        - /tmp
      initialDelaySeconds: 5
      periodSeconds: 5